# Generated by Django 5.2.16 on 2026-07-30 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetconfig',
            name='currency_code',
            field=models.CharField(default='NGN', max_length=5),
        ),
        migrations.AlterField(
            model_name='budgetconfig',
            name='currency_symbol',
            field=models.CharField(default='₦', max_length=5),
        ),
    ]
